services:
  - type: web
    name: veracode-sast-sca-dast-lab
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_URL
        sync: false
      - key: ENTRA_CLIENT_ID
        sync: false
      - key: ENTRA_CLIENT_SECRET
        sync: false
      - key: ENTRA_TENANT_ID
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        sync: false
